---
title: "2024-02-27 Leap Year"
format: html
---

# The Data
```{r}
#| warning: false
#| message: false

library(tidyverse)
library(babynames)
library(praise)

events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-27/events.csv')
births <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-27/births.csv')
deaths <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-02-27/deaths.csv')
```

# Plot
```{r}
babynames |>
  filter(name == "Matthew" | name == "John" | name == "Federica" | name == "Johanna" | name == "Clara") |>
  filter(sex == "F") |>
  ggplot(aes(x = year, y = n, color = name)) +
  geom_line(aes(lty = sex))
```


```{r}
babynames |> filter(name == "Jaguar")
```

```{r}
births <- births |>
  separate(person, c("Fname", "Lname", "other")) 
```

```{r}
leap_names <- births |>  # create a list of duplicate leap names
  group_by(Fname) |>
  summarize(count = n()) |>
  filter(count >= 2) 

leap_names
``` 

```{r}
praise()
```

