---
title: "TidyTuesday 3-19-24 X-Men Moneyball"
format: html
editor: visual
---

# The Data
```{r}
#| warning: false
#| message: false

library(tidyverse)
mutant_moneyball <-
readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-03-19/mutant_moneyball.csv') |>
  mutate(across(`60s_Appearance_Percent`:PPI90s_oStreet, parse_number))
```

# The Plots

Characters comics sold prices vs projected value in the 60s
```{r}
#| warning: false
#| message: false
mutant_moneyball |>
  ggplot(aes(x = PPI60s_wiz, y = PPI60s_ebay)) + 
  geom_point(aes(size = TotalIssues60s)) +
  geom_abline(intercept = 0, slope = 1) +
  ggrepel::geom_label_repel(aes(label = Member)) 

```

Pivoting the data
```{r}
longer<-mutant_moneyball |>
  select(-TotalIssues, -totalIssueCheck, -TotalValue_heritage, -TotalValue_ebay) |>
  pivot_longer(cols=-1, 
                     names_pattern = "(.*\\d\\ds)(.*)", 
                     names_to = c("limit", "name")) |>

  mutate(decade = str_extract(limit,"\\d\\ds"), 
         name1 = str_extract(limit, "[A-Za-z]+")) |>
  
  mutate(variable = paste(name1, name, sep = "")) |>
  select(Member, decade, value, variable) |>
  pivot_wider(names_from = variable, values_from = value)
         
```

Characters comics sold prices vs projected value from different decades
```{r}
longer |>
  #ggplot(aes(x = PPI60s_wiz, y = PPI60s_ebay)) + 
  ggplot(aes(x = PPI_ebay, y = PPI_wiz)) +
  geom_point(aes(size = TotalIssues, color = Member)) +
  geom_abline(intercept = 0, slope = 1) +
  #ggrepel::geom_label_repel(aes(label = Member)) +
  facet_wrap(~decade, scales = "free") +
  theme(legend.position = "none")
```
