---
title: "4-9-24 Eclipse"
---

## The Data
```{r}
#| warning: false
#| message: false
library(tidyverse)
eclipse_annular_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_annular_2023.csv')
eclipse_total_2024 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_total_2024.csv')
eclipse_partial_2023 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_partial_2023.csv')
eclipse_partial_2024 <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2024/2024-04-09/eclipse_partial_2024.csv')
```

## 2024 Data
```{r}
#| warning: false
#| message: false

tot_24 <- eclipse_total_2024 |>
  mutate(time = eclipse_6 - eclipse_1, 
         eclipse = "total") |>
  select(state, name, lat, lon, time, eclipse)

part_24 <- eclipse_partial_2024 |>
  mutate(time = eclipse_5 - eclipse_1,
         eclipse = "partial") |>
  select(state, name, lat, lon, time, eclipse)

eclipse_24 <- rbind(tot_24, part_24) |>
  mutate(time= as.numeric(time))
```


```{r}
#| fig-cap: In blue, the path of the total eclipse. The times represent the difference (in seconds) between when the moon first contants the sun and when the moon last contacts the sun.

library(ggnewscale)
states <- map_data("state")

ggplot(states) +
  geom_polygon(fill = "white", color = "black",
               aes(long, lat, group=group)) +
  geom_point(data = filter(eclipse_24, lat < 51 & lat > 24 & lon < 0 & eclipse == "total"), 
             aes(x = lon, y = lat, color = time), size = 0.01) +
  labs(x = "", y = "") +
  scale_color_gradientn(colors = c("blue", "turquoise")) +
  labs(color = "time of overlap (sec\ntotal eclipse") + 
  new_scale_color() +
  geom_point(data = filter(eclipse_24, lat < 51 & lat > 24 & lon < 0 & eclipse == "partial"), 
             aes(x = lon, y = lat, color = time), size = 0.01) +
  scale_color_gradientn(colors = c("red", "maroon")) +
  ggtitle("2024 solar eclipse") +
  labs(color = "time of overlap (sec\npartial eclipse")
```

## 2023 Data
```{r}
library(tidyverse)

tot_23 <- eclipse_annular_2023 |>
  mutate(time = eclipse_6 - eclipse_1, 
         eclipse = "total") |>
  select(state, name, lat, lon, time, eclipse)

part_23 <- eclipse_partial_2023 |>
  mutate(time = eclipse_5 - eclipse_1,
         eclipse = "partial") |>
  select(state, name, lat, lon, time, eclipse)

eclipse_23 <- rbind(tot_23, part_23) |>
  mutate(time= as.numeric(time))
```

```{r}
#| fig-cap: In blue, the path of the 2023 annualar eclipse. The times represent the difference (in seconds) between when the moon first contants the sun and when the moon last contacts the sun.

library(ggnewscale)
states <- map_data("state")

ggplot(states) +
  geom_polygon(fill = "white", color = "black",
               aes(long, lat, group=group)) +
  geom_point(data = filter(eclipse_23, lat < 51 & lat > 24 & lon < 0 & eclipse == "total"), 
             aes(x = lon, y = lat, color = time), size = 0.01) +
  labs(x = "", y = "") +
  scale_color_gradientn(colors = c("blue", "turquoise")) +
  labs(color = "time of overlap (sec\nannular eclipse") + 
  new_scale_color() +
  geom_point(data = filter(eclipse_23, lat < 51 & lat > 24 & lon < 0 & eclipse == "partial"), 
             aes(x = lon, y = lat, color = time), size = 0.01) +
  scale_color_gradientn(colors = c("red", "maroon")) +
  ggtitle("2023 solar eclipse") +
  labs(color = "time of overlap (sec\npartial eclipse")
```